import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff8f0',
    },
    appHeader: {
      backgroundColor: '#fff',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#fed7aa',
    },
    appHeaderContent: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    logoContainer: {
      width: 48,
      height: 48,
      backgroundColor: '#f97316',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
      transform: [{ rotate: '3deg' }],
    },
    appTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#111827',
    },
    appSubtitle: {
      fontSize: 12,
      color: '#f97316',
      fontWeight: '600',
    },
    statsContainer: {
      flexDirection: 'row',
      gap: 8,
    },
    statBadge: {
      backgroundColor: '#fed7aa',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statText: {
      fontSize: 12,
      color: '#c2410c',
      fontWeight: '600',
    },
    statBadgeRed: {
      backgroundColor: '#fee2e2',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statTextRed: {
      fontSize: 12,
      color: '#dc2626',
      fontWeight: '600',
    },
    tabNav: {
      flexDirection: 'row',
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#fed7aa',
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      gap: 6,
    },
    tabActive: {
      borderBottomWidth: 2,
      borderBottomColor: '#f97316',
    },
    tabText: {
      fontSize: 12,
      color: '#6b7280',
      fontWeight: '600',
    },
    tabTextActive: {
      color: '#f97316',
    },
    tabContent: {
      flex: 1,
      padding: 16,
    },
    heroSection: {
      marginBottom: 24,
    },
    heroTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: '#111827',
      marginBottom: 8,
      textAlign: 'center',
    },
    heroSubtitle: {
      fontSize: 16,
      color: '#6b7280',
      textAlign: 'center',
      lineHeight: 24,
    },
    inputCard: {
      backgroundColor: '#fff',
      borderRadius: 24,
      padding: 20,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 8,
    },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#e5e7eb',
      borderRadius: 16,
      paddingHorizontal:5,
      marginBottom: 5,
    },
    inputIcon: {
      marginRight: 8,
    },
    input: {
      flex: 1,
      paddingVertical: 14,
      fontSize: 16,
      color: '#111827',
    },
    extractButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f97316',
      paddingVertical: 16,
      borderRadius: 16,
      gap: 8,
      marginBottom: 16,
    },
    buttonDisabled: {
      opacity: 0.5,
    },
    buttonLoader: {
      marginRight: 8,
    },
    extractButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    infoBox: {
      backgroundColor: '#fed7aa',
      padding: 12,
      borderRadius: 12,
    },
    infoText: {
      fontSize: 13,
      color: '#9a3412',
    },
    infoBold: {
      fontWeight: '700',
    },
    featureGrid: {
      gap: 16,
    },
    featureCard: {
      backgroundColor: '#fff',
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#fed7aa',
    },
    featureTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 8,
    },
    featureText: {
      fontSize: 14,
      color: '#6b7280',
      marginBottom: 4,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    headerTitle: {
      paddingTop: 40,
      fontSize: 24,
      fontWeight: 'bold',
      color: '#111827',
    },
    addButton: {
      paddingTop: 40,
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    clearButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#ef4444',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      gap: 6,
    },
    clearButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
      backgroundColor: '#fff',
      borderRadius: 24,
      borderWidth: 2,
      borderColor: '#fed7aa',
      borderStyle: 'dashed',
    },
    emptyText: {
      fontSize: 18,
      color: '#6b7280',
      marginTop: 16,
    },
    emptyLink: {
      fontSize: 16,
      color: '#f97316',
      marginTop: 8,
      fontWeight: '600',
    },
    recipeCard: {
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#fed7aa',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    recipeHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    recipeTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#111827',
      flex: 1,
      marginRight: 8,
    },
    recipeMetaContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      marginBottom: 12,
    },
    recipeMeta: {
      fontSize: 13,
      color: '#6b7280',
    },
    tagContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    tag: {
      backgroundColor: '#fed7aa',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
    },
    tagText: {
      fontSize: 12,
      color: '#c2410c',
      fontWeight: '600',
    },
    ingredientsPreview: {
      marginBottom: 12,
    },
    ingredientsTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#374151',
      marginBottom: 6,
    },
    ingredientText: {
      fontSize: 13,
      color: '#6b7280',
      marginBottom: 2,
    },
    moreText: {
      fontSize: 13,
      color: '#f97316',
      fontWeight: '600',
      marginTop: 4,
    },
    recipeActions: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    actionButtonGreen: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#10b981',
      paddingVertical: 10,
      borderRadius: 12,
      gap: 6,
    },
    actionButtonBlue: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3b82f6',
      paddingVertical: 10,
      borderRadius: 12,
      gap: 6,
    },
    actionButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    viewSourceButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      gap: 4,
    },
    viewSourceText: {
      color: '#f97316',
      fontSize: 13,
      fontWeight: '600',
    },
    categorySection: {
      marginBottom: 24,
    },
    categoryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    categoryTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#111827',
    },
    groceryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fed7aa',
      padding: 12,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: '#fed7aa',
    },
    groceryItemChecked: {
      backgroundColor: '#f3f4f6',
      borderColor: '#e5e7eb',
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: '#d1d5db',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    checkboxChecked: {
      backgroundColor: '#10b981',
      borderColor: '#10b981',
    },
    groceryItemContent: {
      flex: 1,
    },
    groceryItemText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#111827',
    },
    groceryItemTextChecked: {
      textDecorationLine: 'line-through',
      color: '#9ca3af',
    },
    groceryItemFrom: {
      fontSize: 12,
      color: '#6b7280',
      marginTop: 2,
    },
    mealCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#fed7aa',
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#fdba74',
    },
    mealContent: {
      flex: 1,
    },
    mealTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 4,
    },
    mealMeta: {
      fontSize: 13,
      color: '#6b7280',
    },
  });
  export default styles;